Domain restore documentation
dnsimple/dnsimple-support pull request #1147
Opened 2024-02-26 00:25 UTC by kntsoriano

This adds the support documentation for domain restore.

To be more specific, this adds the following:
* Add page on how to restore a domain.
* Update specific TLD docs to link to the restoration page.
* Update "What happens when a domain expires page?" to include domain restoration.

2024-02-26 07:39 UTC, OleMchls approved these changes
Please have @itsalyse review the copy :)

2024-02-26 07:39 UTC, OleMchls commented on content/files/restore-domain-form.png
We should not display our ops e-mail address here

2024-02-26 16:49 UTC, stephanoodle requested changes

2024-02-26 16:49 UTC, stephanoodle commented on content/articles/restoring-domain.md
> +The final price of the restore will be the <strong>restore fee plus the standard renewal fee</strong>.
We should mention that the renewal pricing will differ for each TLD.

2024-02-26 16:49 UTC, stephanoodle commented on content/articles/restoring-domain.md
> +If the restoration fails, funds will be released.
We need to tell the customers that they will receive an email once the restore completes, or an email if it fails.

2024-02-27 00:07 UTC, SarahCaminiti1 commented
I've added Alyse and removed myself as I'll be OOO

2024-02-27 04:29 UTC, kntsoriano commented
@SarahCaminiti1 Thanks for letting me know. I'll transfer this to a google doc.

2024-02-27 04:42 UTC, kntsoriano commented
Closing this for now. Created the google doc: https://docs.google.com/document/d/1oLXT8WWirT_PzSgo4T3N_ExFr8v0Gd24ArvUNx6d6lE/edit

2024-02-27 04:42 UTC, closed without merging

2024-02-27 17:11 UTC, stephanoodle commented
> Closing this for now. Created the google doc: https://docs.google.com/document/d/1oLXT8WWirT_PzSgo4T3N_ExFr8v0Gd24ArvUNx6d6lE/edit

FYI this doc looks good to me.